#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/planet.h"
#include "images/start.h"
#include "images/rocket.h"
#include "images/win.h"
#include "images/lose.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  PLAY,
  WIN,
  LOSE,
} GBAState;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //

  REG_DISPCNT = MODE3 | BG2_ENABLE;


  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  //for the state machine
  int bgChanger = 0;

  //the object that you get to move
  Player theRocket;
  theRocket.xPos = 30;
  theRocket.yPos = 30;
  theRocket.xPrev = 30;
  theRocket.yPrev = 30;
  theRocket.xSpeed = 1;
  theRocket.ySpeed = 1;

  int score = 0; //how many goals reached

  //what you hit to lose
  Obstacle thePlanet;
  thePlanet.x = 100;
  thePlanet.y = 100;
  thePlanet.yOld = 100;
  thePlanet.xOld = 100;
  thePlanet.xVel = 1;
  thePlanet.yVel = 1;
  thePlanet.img = planet;

  //to move the goal randomly
  Checkpoint goal;
  goal.x = randint(0, 230);
  goal.y = randint(20, 150);


  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons


    /* TODO: */
    // Manipulate the state machine below as needed // come back to this part !! write all your helper methods first
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (state) {
      case START:

        if (bgChanger == 0) {
          drawFullScreenImageDMA(start);
          bgChanger = 1;
        }

        //drawFullScreenImageDMA() put start screen image in here !!
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
          score = 0;

          thePlanet.x = 100;
          thePlanet.y = 100;
          thePlanet.yOld = 100;
          thePlanet.xOld = 100;

          theRocket.xPos = 30;
          theRocket.yPos = 30;
          theRocket.xPrev = 30;
          theRocket.yPrev = 30;

          fillScreenDMA(YELLOW);
        }
        break;
      case PLAY:

        drawRectDMA(theRocket.yPrev, theRocket.xPrev, 20, 20, YELLOW);
        drawRectDMA(thePlanet.yOld, thePlanet.xOld, 20, 20, YELLOW);
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = PLAY;
          score = 0;

          thePlanet.x = 100;
          thePlanet.y = 100;
          thePlanet.yOld = 100;
          thePlanet.xOld = 100;

          theRocket.xPos = 30;
          theRocket.yPos = 30;
          theRocket.xPrev = 30;
          theRocket.yPrev = 30;
          bgChanger = 0;
          state = START;
        }

        drawImageDMA(theRocket.yPos, theRocket.xPos, 20, 20, rocket);

        theRocket.xPrev = theRocket.xPos;
        theRocket.yPrev = theRocket.yPos;
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && theRocket.xPos < 220) {
          theRocket.xPos++;
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons) && theRocket.xPos > 0) {
          theRocket.xPos--;
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons) && theRocket.yPos > 15) {
          theRocket.yPos--;
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons) && theRocket.yPos < 140) {
          theRocket.yPos++;
        }

        drawRectDMA(goal.y, goal.x, 10, 10, RED); //draw goal
        drawObstacle(thePlanet.x, thePlanet.y);
        thePlanet.xOld = thePlanet.x;
        thePlanet.yOld = thePlanet.y;

        int randX = randint(0, 2);
        int randY = randX;
        //int randY = randint(0, 1);

        if (thePlanet.x == 220) {
          thePlanet.xVel = -1;
        }
        if (thePlanet.x == 0) {
          thePlanet.xVel = 1;
        }
        thePlanet.x = thePlanet.x + thePlanet.xVel*randX;

        if (thePlanet.y == 130) {
          thePlanet.yVel = -1;
        }
        if (thePlanet.y == 20) {
          thePlanet.yVel = 1;
        }
        thePlanet.y = thePlanet.y + thePlanet.yVel*randY;
        thePlanet.img = planet;

        if (theRocket.xPos < thePlanet.x + 20 && theRocket.xPos + 20 > thePlanet.x && theRocket.yPos < thePlanet.y + 20 && theRocket.yPos + 20 > thePlanet.y) {
          bgChanger = 0;
          state = LOSE;
        }

        if (theRocket.xPos < goal.x + 10 && theRocket.xPos + 20 > goal.x && theRocket.yPos < goal.y + 10 && theRocket.yPos + 20 > goal.y) {
          score++;
          drawRectDMA(goal.y, goal.x, 10, 10, YELLOW);
          goal.x = randint(0, 230);
          goal.y = randint(20, 150);
        }

        if (score == 5) {
          bgChanger = 0;
          state = WIN;
        }

        char charBuffer[50];
        snprintf(charBuffer, 50, "Score: %d", score);
        drawRectDMA(5, 180, 60, 10, YELLOW);
        drawString(5, 180, charBuffer, BLACK);

        //drawFullScreenImageDMA() put sea picture here!
        // use arrow keys to move
        // if theRocket touches the goal, add one to points, erase goal, make a new goal
        // if points == 5, state = WIN
        // if theRocket touches planet, state = LOSE
        // state = ?
        break;
      case WIN:

        //if number of checkpoints equals 5
        //put win screen image in here !!
        if (bgChanger == 0) {
          drawFullScreenImageDMA(win);
          bgChanger = 1;
        }

        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = PLAY;
          score = 0;

          thePlanet.x = 100;
          thePlanet.y = 100;
          thePlanet.yOld = 100;
          thePlanet.xOld = 100;

          theRocket.xPos = 30;
          theRocket.yPos = 30;
          theRocket.xPrev = 30;
          theRocket.yPrev = 30;

          bgChanger = 0;
          state = START;

        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
          score = 0;

          thePlanet.x = 100;
          thePlanet.y = 100;
          thePlanet.yOld = 100;
          thePlanet.xOld = 100;

          theRocket.xPos = 30;
          theRocket.yPos = 30;
          theRocket.xPrev = 30;
          theRocket.yPrev = 30;
          fillScreenDMA(YELLOW);
        }

        // state = ?
        break;
      case LOSE:

        //put lose screen image in here
        if (bgChanger == 0) {
          drawFullScreenImageDMA(lose);
          bgChanger = 1;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = PLAY;
          score = 0;

          thePlanet.x = 100;
          thePlanet.y = 100;
          thePlanet.yOld = 100;
          thePlanet.xOld = 100;

          theRocket.xPos = 30;
          theRocket.yPos = 30;
          theRocket.xPrev = 30;
          theRocket.yPrev = 30;

          bgChanger = 0;
          state = START;
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
          score = 0;

          thePlanet.x = 100;
          thePlanet.y = 100;
          thePlanet.yOld = 100;
          thePlanet.xOld = 100;

          theRocket.xPos = 30;
          theRocket.yPos = 30;
          theRocket.xPrev = 30;
          theRocket.yPrev = 30;

          fillScreenDMA(YELLOW);
        }

        // state = ?
        break;
    }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }

  UNUSED(previousButtons);  // You can remove this once previousButtons is used

  return 0;

}

//draws obstacle (planet? maybe) that will move and that the player must avoid
//might replace this with a picture of a planet tbh?
int drawObstacle(int x, int y) {
   drawImageDMA(y, x, 20, 20, planet);
    return 0;
  //drawRectDMA(planet.x, planet.y, 5, 5, GRAY); //this should not be a rectangle (try using an image?)
}
